name: Generate M3U Playlist

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install mongoose

      - name: Generate playlist.m3u
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: node generate.js

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          git add playlist.m3u
          git diff --staged --quiet && echo "✅ No changes" && exit 0
          git commit -m "🔄 Update playlist [$(date +'%Y-%m-%d %H:%M')]"
          git push origin main
